CREATE TABLE COM_CUSTOMER (
    COM_CUSTOMER_ID INT IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE SALES_SO (
    SALES_SO_ID INT IDENTITY(1,1) PRIMARY KEY,
    SO_NO VARCHAR(20) NOT NULL UNIQUE,
    ORDER_DATE DATETIME NOT NULL,
    COM_CUSTOMER_ID INT NOT NULL,
    ADDRESS VARCHAR(500)
);

CREATE TABLE SALES_SO_LITEM (
    SALES_SO_LITEM_ID INT IDENTITY(1,1) PRIMARY KEY,
    SALES_SO_ID INT NOT NULL,
    ITEM_NAME VARCHAR(100) NOT NULL,
    QUANTITY INT NOT NULL CHECK (QUANTITY > 0),
    PRICE FLOAT NOT NULL CHECK (PRICE > 0)
);


ALTER TABLE SALES_SO 
    ADD CONSTRAINT FK_SALES_SO_CUSTOMER 
    FOREIGN KEY (COM_CUSTOMER_ID) REFERENCES COM_CUSTOMER(COM_CUSTOMER_ID);

ALTER TABLE SALES_SO_LITEM 
    ADD CONSTRAINT FK_SALES_SO_LITEM_SO 
    FOREIGN KEY (SALES_SO_ID) REFERENCES SALES_SO(SALES_SO_ID) 
    ON DELETE CASCADE;
GO


INSERT INTO COM_CUSTOMER (CUSTOMER_NAME) VALUES 
('PT Budi Karya'),
('CV Maju Bersama'),
('Toko Jaya Abadi');
GO